uv run -m codes.methods.train_seq2seq \
    --input-dir data/postprocess/ \
    --output-dir data/postprocess/models/seq2seq_bart/ \
    --embeddings data/postprocess/embeddings/best.pt \
    --epochs 100 \
    --print_batch_step 10 \
    --batch_size 64 \
    --lr 0.001 \
    --num_workers 12 \
    --scale 10 \
    --phonetic "BARTPhoEncoder" \
    --transform "PMAMWithBART" \
    --bypass_check \
    --save_res_path data/postprocess/models/seq2seq_bart/results.txt