uv run -m codes.methods.train_seq2seq \
    --input-dir data/postprocess/segmented \
    --output-dir codes/models/seq2seq/ \
    --embeddings data/postprocess/embeddings/best.pt \
    --emb_dims 256 \
    --hidden_size 384 \
    --epochs 100 \
    --print_batch_step 10 \
    --batch_size 64 \
    --lr 0.001 \
    --num_workers 8 \
    --fusion "Fusion" \
    --encoder "Identity" \
    --bypass_check \
    --save_res_path codes/models/seq2seq/results.txt